### ISSUE TITLE
Documentation should state that one needs to explicitly free xdoc objects

### ISSUE THREAD

**Issue by robertfeldt** [JuliaLang/LightXML.jl#16]
I had problems with a long-running optimization that was leaking memory. The cause seems to be that xdoc objects it created in each function/fitness eval needs to be explicilty freed. Details in this google groups thread:

https://groups.google.com/forum/#!topic/julia-users/ycFiuyjSgdA

Until finalizers are added to the code base, I suggest the LightXML front page is updated to clearly state that the user must take care to free objects.

**Comment by tkelman** [comment]
If you have a suggested wording, a PR would be welcome.

**Comment by robertfeldt** [comment]
Not sure of the wording but at least there is now a proposed note about it in the README.

**Comment by tkelman** [comment]
Closed by #18. Still work to be done on this though, ref #17...
