### ISSUE TITLE
Installing LightXML fails

### ISSUE THREAD

**Issue by ArthurZ** [JuliaLang/LightXML.jl#23]
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
....
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 1/5 downloading: http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 2/5 downloading: http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 3/5 downloading: http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 4/5 downloading: http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
WARNING: Unknown download failure, error code: 2148270088
WARNING: Retry 5/5 downloading: http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
WARNING: received error 0 while downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
WARNING: Could not update Julia's gcc dlls, some WinRPM packages may not work.
Error was: Package candidate for libgfortran3 not found
Try running Julia as administrator and calling `Pkg.build("WinRPM")`.
...
========================================[ ERROR: LightXML ]=========================================

None of the selected providers can install dependency libxml2-2.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\AZ\.babun\cygwin\home\AZ\.julia\v0.3\LightXML\deps\build.jl, in expression starting on line 11

====================================================================================================
I am able to install other packages.

**Comment by tkelman** [comment]
What's your `versioninfo` ? Do those other packages that you're able to install include anything that depends on winrpm, like HDF5, ZMQ, Cbc, etc?

**Comment by ArthurZ** [comment]
It is 0.3.7
I am not sure how to tell, I installed JSON, ODBC, DataFrames so far.

**Comment by tkelman** [comment]
In that case the gcc dll's thing that WinRPM is doing shouldn't really be needed. Try running the following:
```
for lib in ["libgfortran-3", "libquadmath-0", "libstdc++-6", "libssp-0",
        WORD_SIZE==32 ? "libgcc_s_sjlj-1" : "libgcc_s_seh-1"]
    cp(joinpath(JULIA_HOME, lib * ".dll"), joinpath(JULIA_HOME, lib * "-copy.dll"))
end
Pkg.build("LightXML")
```

**Comment by ArthurZ** [comment]
Errors again in https://gist.github.com/ArthurZ/6683048fec33e778288b

**Comment by tkelman** [comment]
Hm, are you behind some kind of proxy or something?

Try opening the file C:\Users\AZ.babun\cygwin\home\AZ.julia\v0.3\WinRPM\src\WinRPM.jl, commenting out the `download` function on these lines https://github.com/JuliaLang/WinRPM.jl/blob/a0d80507c46ef4ce0f1a5636425ff8559c048673/src/WinRPM.jl#L44-L72, and replace it with this:

```
function download(source::String; retry = 5)
    return readall(`powershell -Command "(new-object net.webclient).DownloadString(\"$source\")"`), 200
end
```
Then restart Julia and see if `Pkg.build("LightXML")` works.

**Comment by ArthurZ** [comment]
It is a corporate laptop, but I am on home network.
I did commented that portion out, but getting errors still
julia> Pkg.build("LightXML")
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
==============================================================================================================[ ERROR: WinRPM ]==============================================================================================================

"ErrorException(\"Error parsing document : 0\"), not well-formed (invalid token), 6, 80, 266"
while loading C:\Users\Arthur.Zubarev\.babun\cygwin\home\Arthur.Zubarev\.julia\v0.3\WinRPM\deps\build.jl, in expression starting on line 2

=============================================================================================================================================================================================================================================
INFO: Building LightXML
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
=============================================================================================================[ ERROR: LightXML ]=============================================================================================================

"ErrorException(\"Error parsing document : 0\"), not well-formed (invalid token), 6, 80, 266"
while loading C:\Users\Arthur.Zubarev\.babun\cygwin\home\Arthur.Zubarev\.julia\v0.3\LightXML\deps\build.jl, in expression starting on line 11

=============================================================================================================================================================================================================================================

==============================================================================================================[ BUILD ERRORS ]===============================================================================================================

WARNING: WinRPM and LightXML had build errors.

 - packages with build errors remain installed in C:\Users\Arthur.Zubarev\.babun\cygwin\home\Arthur.Zubarev\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("WinRPM", "LightXML")`
 - build a single package by running its `deps/build.jl` script

**Comment by tkelman** [comment]
What does ```readall(`powershell -Command "(new-object net.webclient).DownloadString(\"http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml\")"`)``` return? Can you access that url in a regular browser?

**Comment by ArthurZ** [comment]
In FF I get Object not found!

The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.
Error 404
download.opensuse.org
Sat Apr 4 00:16:15 2015
Apache/2.2.12 (Linux/SUSE)

**Comment by ArthurZ** [comment]
Executing the line
julia> readall(`powershell -Command "(new-object net.webclient).DownloadString(\"http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml\")"`)
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<repomd xmlns=\"http://linux.duke.edu/metadata/repo\" xmlns:rpm=\"http://linux.duke.edu/metadata/rpm\">\r\n <revision>1428095718</revision>\r\n <tags>\r\n   <repo>obsrepository://build.opensuse.org/windows:mingw:win32/openSUSE_13.1</repo>\r\n </tags>\r\n<data type=\"filelists\">\r\n  <checksum type=\"sha256\">6a4df47c6772234efd09f95320d8f4f1b3823be89fa605009f4b035d5e0a2dbf</checksum>\r\n  <open-checksum type=\"sha256\">d37eeeb15e84944e32ca382a0df9438e522bda89237d3be4d2ad26302cb04677</open-chec\r\nksum>\r\n  <location href=\"repodata/6a4df47c6772234efd09f95320d8f4f1b3823be89fa605009f4b035d5e0a2dbf-filelists.xml.\r\ngz\"/>\r\n  <timestamp>1428095722</timestamp>\r\n  <size>1143647</size>\r\n  <open-size>17704164</open-size>\r\n</data>\r\n<data type=\"other\">\r\n  <checksum type=\"sha256\">bfffc50df25ef1c6800735840a0534007c596221d5498c3f8254a89c3bb7196f</checksum>\r\n  <open-checksum type=\"sha256\">482feb3b876b9c56a397e854add9f81da62ea26b75574be7144ab8d0ce5506cb</open-chec\r\nksum>\r\n  <location href=\"repodata/bfffc50df25ef1c6800735840a0534007c596221d5498c3f8254a89c3bb7196f-other.xml.gz\"/\r\n>\r\n  <timestamp>1428095722</timestamp>\r\n  <size>121425</size>\r\n  <open-size>663791</open-size>\r\n</data>\r\n<data type=\"primary\">\r\n  <checksum type=\"sha256\">428f979eb6bc72eb4d3432a41f71dfda730948c773978af341cdaa8239e8262e</checksum>\r\n  <open-checksum type=\"sha256\">d02f44dfde4a8bb018a5f70d67471322e2e375392d271827833939973b21555f</open-chec\r\nksum>\r\n  <location href=\"repodata/428f979eb6bc72eb4d3432a41f71dfda730948c773978af341cdaa8239e8262e-primary.xml.gz\r\n\"/>\r\n  <timestamp>1428095722</timestamp>\r\n  <size>366319</size>\r\n
<open-size>3377375</open-size>\r\n</data>\r\n</repomd>\r\n\r\n"

**Comment by tkelman** [comment]
Bizarre. So those are the checksums, timestamps, and sizes from that xml file, but none of the xml tags are coming through when you download them. How about
```readall(`curl http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml`)```, does that look the same?

**Comment by tkelman** [comment]
For reference, this is what the file looks like when I download it: https://gist.github.com/tkelman/aa3002933364dd3ce885

I've never heard of a corporate download filter that removes tags from xml files, but I guess there are stranger things out there.

**Comment by ArthurZ** [comment]
Rebooted. Now was able to get the file right looks like
julia> readall(`curl http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml`)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1620  100  1620    0     0   4512      0 --:--:-- --:--:-- --:--:--  4512
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<repomd xmlns=\"http://linux.duke.edu/metadata/repo\" xmlns:rpm=\"http://linux.duke.edu/metadata/rpm\">\n <revision>1428095718</revision>\n <tags>\n   <repo>obsrepository://build.opensuse.org/windows:mingw:win32/openSUSE_13.1</repo>\n </tags>\n<data type=\"filelists\">\n  <checksum type=\"sha256\">6a4df47c6772234efd09f95320d8f4f1b3823be89fa605009f4b035d5e0a2dbf</checksum>\n  <open-checksum type=\"sha256\">d37eeeb15e84944e32ca382a0df9438e522bda89237d3be4d2ad26302cb04677</open-checksum>\n  <location href=\"repodata/6a4df47c6772234efd09f95320d8f4f1b3823be89fa605009f4b035d5e0a2dbf-filelists.xml.gz\"/>\n  <timestamp>1428095722</timestamp>\n  <size>1143647</size>\n  <open-size>17704164</open-size>\n</data>\n<data type=\"other\">\n  <checksum type=\"sha256\">bfffc50df25ef1c6800735840a0534007c596221d5498c3f8254a89c3bb7196f</checksum>\n  <open-checksum type=\"sha256\">482feb3b876b9c56a397e854add9f81da62ea26b75574be7144ab8d0ce5506cb</open-checksum>\n  <location href=\"repodata/bfffc50df25ef1c6800735840a0534007c596221d5498c3f8254a89c3bb7196f-other.xml.gz\"/>\n  <timestamp>1428095722</timestamp>\n  <size>121425</size>\n  <open-size>663791</open-size>\n</data>\n<data type=\"primary\">\n  <checksum type=\"sha256\">428f979eb6bc72eb4d3432a41f71dfda730948c773978af341cdaa8239e8262e</checksum>\n  <open-checksum type=\"sha256\">d02f44dfde4a8bb018a5f70d67471322e2e375392d271827833939973b21555f</open-checksum>\n  <location href=\"repodata/428f979eb6bc72eb4d3432a41f71dfda730948c773978af341cdaa8239e8262e-primary.xml.gz\"/>\n  <timestamp>1428095722</timestamp>\n  <size>366319</size>\n  <open-size>3377375</open-size>\n</data>\n</repomd>\n"

**Comment by ArthurZ** [comment]
And then attempted to install LightXML:
julia> Pkg.add("LightXML")
INFO: Cloning cache of LightXML from git://github.com/lindahua/LightXML.jl.git
INFO: Installing LightXML v0.1.6
INFO: Building LibCURL
WARNING: The URLParse.jl package has been deprecated in favour of JuliaWeb/URIParser.jl
https://github.com/JuliaWeb/URIParser.jl
As of Julia 0.4 this package will no longer be installable
through `Pkg.add`. Please convert your code accordingly.
WARNING: encounted invalid data while parsing repomd
Warning: error initializing module WinRPM:
"ErrorException("Error parsing document : 0"), not well-formed (invalid token), 1, 1, 1"
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/428f979eb6bc72eb4d3432a41f71dfda730948c773978af341cdaa8239e8262e-primary.xml.gz
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/408889c3b23a997fe9c414ff7989d8d7591d76f2ac0e844f88c7aded75ff9ea8-primary.xml.gz
INFO: Packages to install: libgpg-error6-0, libgcrypt20, libsqlite3-0, libintl8, mozilla-nspr, mozilla-nss, libidn11, zlib1, libssh2-1, libcurl4
INFO: Downloading: libgpg-error6-0
INFO: Extracting: libgpg-error6-0
INFO: Downloading: libgcrypt20
INFO: Extracting: libgcrypt20
INFO: Downloading: libsqlite3-0
INFO: Extracting: libsqlite3-0
INFO: Downloading: libintl8
INFO: Extracting: libintl8
INFO: Downloading: mozilla-nspr
INFO: Extracting: mozilla-nspr
INFO: Downloading: mozilla-nss
INFO: Extracting: mozilla-nss
INFO: Downloading: libidn11
INFO: Extracting: libidn11
INFO: Downloading: zlib1
INFO: Extracting: zlib1
INFO: Downloading: libssh2-1
INFO: Extracting: libssh2-1
INFO: Downloading: libcurl4
INFO: Extracting: libcurl4
INFO: Complete
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.xml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.xml
INFO: Building LightXML
============================================[ ERROR: LightXML ]============================================


None of the selected providers can install dependency libxml2.
Use BinDeps.debug(package_name) to see available providers

while loading C:\Users\Arthur.Zubarev\.julia\v0.3\LightXML\deps\build.jl, in expression starting on line 11


===========================================================================================================


=============================================[ BUILD ERRORS ]==============================================


WARNING: LightXML had build errors.

 - packages with build errors remain installed in C:\Users\Arthur.Zubarev\.julia\v0.3
 - build the package(s) and all dependencies with `Pkg.build("LightXML")`
 - build a single package by running its `deps/build.jl` script

===========================================================================================================

INFO: Package database updated
INFO: METADATA is out-of-date — you may not have the latest version of LightXML
INFO: Use `Pkg.update()` to get the latest versions of your packages

**Comment by ArthurZ** [comment]
Ran the suggested Pkg.update() 
got
INFO: Building LightXML
INFO: Packages to install: libxml2-2
INFO: Downloading: libxml2-2
INFO: Extracting: libxml2-2
INFO: Complete
and then using LightXML went through - huzzah!

**Comment by tkelman** [comment]
That's good to see. You may want to revert any changes you made to LightXML so it can update cleanly in the future (unless those were responsible for it working, it would be good to determine for sure). The version of the file from curl was also missing the xml tags and I'm really not sure why. But at least now I have a concrete example of what might lead to the "Error parsing document."

**Comment by ArthurZ** [comment]
Thank you for your help! AFAIK I did not any. I reverted back to the original file.

**Comment by tkelman** [comment]
Sorry, I meant WinRPM. If you get a chance to test whether ZMQ, HDF5, or other packages from WinRPM work correctly that would be useful. Otherwise I guess we should close this? It was really an issue for WinRPM to begin with anyway.

**Comment by ArthurZ** [comment]
I rather think the issue was with the OpenSUSE build service for message 
Error 404
download.opensuse.org
Sat Apr 4 00:16:15 2015
Apache/2.2.12 (Linux/SUSE)

**Comment by ArthurZ** [comment]
I am able to install HDF5 for example.
On a separate note I sent you a private message.
Thank you!

**Comment by tkelman** [comment]
Maybe we'll blame this one on the opensuse build service occasionally being flaky, if everything is working fine now. Sorry for the trouble, there are some things I've been meaning to try with WinRPM that might be able to improve the reliability a little bit.
