### ISSUE TITLE
Redesign floyd_warshall_shortest_paths?

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/LightXML.jl#24]
`floyd_warshall_shortest_paths` is quite a long function name. Given that the name Floyd-Warshall is sufficient to identify the algorithm, can we rename this function to `floyd_warshall`?

Also, can we make `FloydWarshallState.dists` a matrix rather than the vector of vectors that it currently is? The distance matrix is a key input to graph layout algorithms, such as `GraphLayout.layout_stressmajorize_adj`.

**Comment by tkelman** [comment]
Wrong repo?

**Comment by jiahao** [comment]
Fail. Thanks.
