### ISSUE TITLE
Feature Request: Parsing HTML Files or Strings

### ISSUE THREAD

**Issue by bkomboz** [JuliaLang/LightXML.jl#36]
This is a feature request/question: What do you think about adding support for parsing HTML files and strings to `LightXML.jl` via the `HTMLparser` module of `libxml2`? 

Two possible strategies to implement this functionality come to my mind:
1. Adding an argument to `parse_file` indicating whether it is a XML or a HTML file which has to be parsed and then internally chosing the corresponding `libxml2` function.
2. Renaming `parse_file` (and similar functions) to `parse_xml[file]` [thus breaking the existing api] and adding `parse_html[file]` (and similar functions).

In addition one would have to think how to represent HTML documents (e.g., a separate `HTMLDocument` type which has a common supertype with the existing `XMLDocument` type?)

What do you think? I would love to have this functionality and would vote for implementation strategy 2. with some transition phase for depracating `parse_file` and similar functions. Overall I think it is cleaner. I could try to set up a prototype if there is support for this feature.

**Comment by tkelman** [comment]
I wouldn't be opposed to exposing the C API if it's always present (can libxml2 be configured to not include the html parsing functionality?) but generally I think specialized html types would be better done in another package. Or `parse_html` could be added without breaking the api.

**Comment by bkomboz** [comment]
Thanks for your response! I looked at the source code and it is possible to turn off HTML parsing functionality when compiling the package. It is activated by default. I started writing a prototype based on a fork of the existing `LightXML.jl` package and it integrates fine with some glue code. I added `parse_htmlfile` and `parse_htmlstring` functions, renamed `parse_file` and `parse_string` to `parse_xmlfile` and `parse_xmlstring` and provided glue code functions `parse_file` and `parse_string` for backward compatibility (with a warning that these functions might be removed in the future.) With this functionality, existing tests work fine. 

However, I also think a separate `HTMLDocument` type will be necessary as not every functionality for `XMLDocument`'s will make sense for `HTMLDocument`'s and vice versa. By unioning the two types, one could implement shared functionality.

I am fine with moving this stuff to a separate package `LightHTML.jl` also I can imagina that at some point in the future, both things could be merged into one parser package.

**Comment by tkelman** [comment]
There are also other dedicated HTML parser packages out there, Gumbo.jl for example (might not be toi actively maintained right now) or other libraries that have not yet been wrapped in Julia.

Adding features doesn't seem like a very good reason to break the API, I really think that should be avoided if it isn't absolutely necessary.

**Comment by bkomboz** [comment]
@tkelman: Thanks for pointing out `Gumbo.jl`. I stumbled uppon it and it is nice but specifically designed for HTML5. My impression is that it is not yet as mature as `libxml2` and also misses some features already present in `libxml2`. 

Re API break: Please see my updated answer above. With two document types, no break of the existing API will happen.

**Comment by tkelman** [comment]
I don't think it's necessary to add a deprecation warning about possible removal of the current API. Any HTML-specific functionality should be separate and under different names and not require existing users of the package to change their code for general-purpose xml.

**Comment by nalimilan** [comment]
I would say adding these features in LightXML makes sense as a lot of the API is shared between XML and HTML. But as @bkomboz noted, no API break is needed: `parse_file` can be made equivalent to `parse_file(XMLDocument, ...)`, and the new HTML features be available under `parse_file(HTMLDocument, ...)`. Other ways of passing this argument could also be used (symbol, boolean...).

**Comment by bkomboz** [comment]
Thanks for your feedback! Actually, I am not sure if my above proposed implementation of `parse_file(XMLDocument, ...)` and `parse_file(HTMLDocument, ...)` really makes sense as the first argument is currently either a string or a filename. One could wrap this in a special filetype and do some checks before trying to parse it but this also creates some overhead compared to the current implementation. The current implementation/interface is, just to be clear:

     parse_file(filename::AbstractString)
     parse_file(filename::AbstractString, encoding, options::Integer)
     parse_string(s::AbstractString)

I added:

     parse_xmlfile(filename::AbstractString)
     parse_xmlfile(filename::AbstractString, encoding, options::Integer)
     parse_xmlstring(s::AbstractString)
     parse_htmlfile(filename::AbstractString, encoding)
     parse_htmlfile(filename::AbstractString, encoding, options::Integer)
     parse_htmlstring(s::AbstractString, baseURL, encoding, options::Integer)
    
and kept the initial functions as wrapper pointing to the `parse_xml[...]` versions.

I understand your concern of not breaking the current API, @tkelman, therefore I would suggest to keep things as above without any deprecation warning in `parse_file` and `parse_string`. So everyone can use the package as before but there is additional HTML parsing functionality and additional glue code for consistency. What I don't like is something like:

     parse_file(filename::AbstractString)
     parse_file(filename::AbstractString, encoding, options::Integer)
     parse_string(s::AbstractString)
     parse_htmlfile(filename::AbstractString, encoding)
     parse_htmlfile(filename::AbstractString, encoding, options::Integer)
     parse_htmlstring(s::AbstractString, baseURL, encoding, options::Integer)
    
I don't think this is a clean and consistent interface and also indicates that HTML parsing somewhat a special case.

Concerning the return values of these functions I suggest two types, the already existing `XMLDocument` type and an `HTMLDocument` type which has to be implemented. Shared functionality can be based on the union for these types and specific functions can be set up for each type individually. I don't think there is any API break/change necessary for these things.

What do you think? If you agree with the current version (wrapper for compatibility + specific parse functions), I will go ahead and implement it fully. Otherwhise I suggest I create a new package `LightHTML.jl` which has all the HTML stuff in it.

**Comment by tkelman** [comment]
HTML parsing **is** a special case. It's new untested functionality that has not been written yet, contributed by someone who's totally new to the community. I don't doubt that you're technically capable, but right now there's a non-negligible chance that you might write this html code then vanish without maintaining it going forward (as the original author of this package has done). So I think you should aim to add new functionality in a minimally disruptive way, get it into the package and tested first. Then long term we could maybe think about refactoring to make HTML functionality less of a second-class citizen. But it's going to have to start that way, since it doesn't exist yet. You'd have more freedom to design things however you like if you use a separate package, so it depends how much code will really be shared.

**Comment by bkomboz** [comment]
Ok, I understand your point. I cannot completely oversee how much overlap there will be. Some yes, but probably not too much. I therefore suggest that I create a separate package `LightHTML.jl` which focuses fully on HTML parsing with `libxml2`. I will try to design it in a way compatible with `LightXML.jl` so that users of this package can easily use it if wanted and we're able to join the two packages in the future if we want to and if it makes sense.

Thanks for your feedback! I'll close this issue now.

**Comment by nalimilan** [comment]
@bkomboz The pattern `parse_file(XMLDocument, ...)` and `parse_file(HTMLDocument, ...)` is quite common in Julia. It imposes no overhead nor any dispatch ambiguity. The other arguments can come after the type in their current order.
